// <auto-generated />
using System;
using ArmazingXStock.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ArmazingXStock.Api.Migrations
{
    [DbContext(typeof(ArmazingXStockContext))]
    [Migration("20260910022757_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("ArmazingXStock.Api.Models.Armazem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("varchar(5)");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Descricao")
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("Armazens", t =>
                        {
                            t.HasCheckConstraint("CK_Armazem_Codigo_Length", "CHAR_LENGTH(Codigo) = 5");
                        });
                });

            modelBuilder.Entity("ArmazingXStock.Api.Models.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.ToTable("Categorias");
                });

            modelBuilder.Entity("ArmazingXStock.Api.Models.Corredor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ArmazemId")
                        .HasColumnType("int");

                    b.Property<bool>("Ativo")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("varchar(3)");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("ArmazemId", "Codigo")
                        .IsUnique();

                    b.HasIndex("ArmazemId", "Nome")
                        .IsUnique();

                    b.ToTable("Corredores", t =>
                        {
                            t.HasCheckConstraint("CK_Corredor_Codigo_Length", "CHAR_LENGTH(Codigo) = 3");
                        });
                });

            modelBuilder.Entity("ArmazingXStock.Api.Models.Endereco", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("CapacidadeMaxima")
                        .HasColumnType("int");

                    b.Property<string>("CodigoCompleto")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("varchar(25)");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("NivelId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CodigoCompleto")
                        .IsUnique();

                    b.HasIndex("NivelId");

                    b.ToTable("Enderecos", t =>
                        {
                            t.HasCheckConstraint("CK_Endereco_CapacidadeMaxima_NonNegative", "CapacidadeMaxima >= 0");

                            t.HasCheckConstraint("CK_Endereco_CodigoCompleto_Length", "CHAR_LENGTH(CodigoCompleto) = 25");
                        });
                });

            modelBuilder.Entity("ArmazingXStock.Api.Models.Fornecedor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("CNPJ")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("varchar(14)");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("NomeFantasia")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("RazaoSocial")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("CNPJ")
                        .IsUnique();

                    b.ToTable("Fornecedores", t =>
                        {
                            t.HasCheckConstraint("CK_Fornecedor_CNPJ_Length", "CHAR_LENGTH(CNPJ) = 14");
                        });
                });

            modelBuilder.Entity("ArmazingXStock.Api.Models.Modulo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("varchar(3)");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("RuaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RuaId", "Codigo")
                        .IsUnique();

                    b.ToTable("Modulos", t =>
                        {
                            t.HasCheckConstraint("CK_Modulo_Codigo_Length", "CHAR_LENGTH(Codigo) = 3");
                        });
                });

            modelBuilder.Entity("ArmazingXStock.Api.Models.Movimentacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataMovimentacao")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("PosicaoDestinoId")
                        .HasColumnType("int");

                    b.Property<int?>("PosicaoOrigemId")
                        .HasColumnType("int");

                    b.Property<int>("QuantidadeMovimentada")
                        .HasColumnType("int");

                    b.Property<int>("TipoMovimentacao")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PosicaoDestinoId");

                    b.HasIndex("PosicaoOrigemId", "PosicaoDestinoId");

                    b.ToTable("Movimentacoes", t =>
                        {
                            t.HasCheckConstraint("CK_Movimentacao_QuantidadeMovimentada_Positive", "QuantidadeMovimentada > 0");
                        });
                });

            modelBuilder.Entity("ArmazingXStock.Api.Models.Nivel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("varchar(3)");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("ModuloId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ModuloId", "Codigo")
                        .IsUnique();

                    b.ToTable("Niveis", t =>
                        {
                            t.HasCheckConstraint("CK_Nivel_Codigo_Length", "CHAR_LENGTH(Codigo) = 3");
                        });
                });

            modelBuilder.Entity("ArmazingXStock.Api.Models.PosicaoEstoque", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataAtualizacao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("EnderecoId")
                        .HasColumnType("int");

                    b.Property<int>("ProdutoId")
                        .HasColumnType("int");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProdutoId");

                    b.HasIndex("EnderecoId", "ProdutoId")
                        .IsUnique();

                    b.ToTable("PosicoesEstoque", t =>
                        {
                            t.HasCheckConstraint("CK_PosicaoEstoque_Quantidade_NonNegative", "Quantidade >= 0");
                        });
                });

            modelBuilder.Entity("ArmazingXStock.Api.Models.Produto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int>("EstoqueMinimo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("SKU")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("varchar(8)");

                    b.Property<int>("TipoProdutoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SKU")
                        .IsUnique();

                    b.HasIndex("TipoProdutoId");

                    b.ToTable("Produtos", t =>
                        {
                            t.HasCheckConstraint("CK_Produto_EstoqueMinimo_NonNegative", "EstoqueMinimo >= 0");

                            t.HasCheckConstraint("CK_Produto_SKU_Length", "CHAR_LENGTH(SKU) = 8");
                        });
                });

            modelBuilder.Entity("ArmazingXStock.Api.Models.ProdutoFornecedor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("FornecedorId")
                        .HasColumnType("int");

                    b.Property<int>("ProdutoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FornecedorId");

                    b.HasIndex("ProdutoId", "FornecedorId")
                        .IsUnique();

                    b.ToTable("ProdutosFornecedores");
                });

            modelBuilder.Entity("ArmazingXStock.Api.Models.Rua", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("varchar(3)");

                    b.Property<int>("CorredorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("CorredorId", "Codigo")
                        .IsUnique();

                    b.HasIndex("CorredorId", "Nome")
                        .IsUnique();

                    b.ToTable("Ruas", t =>
                        {
                            t.HasCheckConstraint("CK_Rua_Codigo_Length", "CHAR_LENGTH(Codigo) = 3");
                        });
                });

            modelBuilder.Entity("ArmazingXStock.Api.Models.TipoProduto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("CategoriaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("Nome", "CategoriaId")
                        .IsUnique();

                    b.ToTable("TiposProdutos");
                });

            modelBuilder.Entity("ArmazingXStock.Api.Models.Corredor", b =>
                {
                    b.HasOne("ArmazingXStock.Api.Models.Armazem", "Armazem")
                        .WithMany("Corredores")
                        .HasForeignKey("ArmazemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Armazem");
                });

            modelBuilder.Entity("ArmazingXStock.Api.Models.Endereco", b =>
                {
                    b.HasOne("ArmazingXStock.Api.Models.Nivel", "Nivel")
                        .WithMany("Enderecos")
                        .HasForeignKey("NivelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Nivel");
                });

            modelBuilder.Entity("ArmazingXStock.Api.Models.Modulo", b =>
                {
                    b.HasOne("ArmazingXStock.Api.Models.Rua", "Rua")
                        .WithMany("Modulos")
                        .HasForeignKey("RuaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Rua");
                });

            modelBuilder.Entity("ArmazingXStock.Api.Models.Movimentacao", b =>
                {
                    b.HasOne("ArmazingXStock.Api.Models.PosicaoEstoque", "PosicaoDestino")
                        .WithMany()
                        .HasForeignKey("PosicaoDestinoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ArmazingXStock.Api.Models.PosicaoEstoque", "PosicaoOrigem")
                        .WithMany()
                        .HasForeignKey("PosicaoOrigemId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("PosicaoDestino");

                    b.Navigation("PosicaoOrigem");
                });

            modelBuilder.Entity("ArmazingXStock.Api.Models.Nivel", b =>
                {
                    b.HasOne("ArmazingXStock.Api.Models.Modulo", "Modulo")
                        .WithMany("Niveis")
                        .HasForeignKey("ModuloId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Modulo");
                });

            modelBuilder.Entity("ArmazingXStock.Api.Models.PosicaoEstoque", b =>
                {
                    b.HasOne("ArmazingXStock.Api.Models.Endereco", "Endereco")
                        .WithMany()
                        .HasForeignKey("EnderecoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ArmazingXStock.Api.Models.Produto", "Produto")
                        .WithMany()
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Endereco");

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("ArmazingXStock.Api.Models.Produto", b =>
                {
                    b.HasOne("ArmazingXStock.Api.Models.TipoProduto", "TipoProduto")
                        .WithMany("Produtos")
                        .HasForeignKey("TipoProdutoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TipoProduto");
                });

            modelBuilder.Entity("ArmazingXStock.Api.Models.ProdutoFornecedor", b =>
                {
                    b.HasOne("ArmazingXStock.Api.Models.Fornecedor", "Fornecedor")
                        .WithMany("ProdutosFornecedores")
                        .HasForeignKey("FornecedorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ArmazingXStock.Api.Models.Produto", "Produto")
                        .WithMany("ProdutosFornecedores")
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Fornecedor");

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("ArmazingXStock.Api.Models.Rua", b =>
                {
                    b.HasOne("ArmazingXStock.Api.Models.Corredor", "Corredor")
                        .WithMany("Ruas")
                        .HasForeignKey("CorredorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Corredor");
                });

            modelBuilder.Entity("ArmazingXStock.Api.Models.TipoProduto", b =>
                {
                    b.HasOne("ArmazingXStock.Api.Models.Categoria", "Categoria")
                        .WithMany("TiposProdutos")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("ArmazingXStock.Api.Models.Armazem", b =>
                {
                    b.Navigation("Corredores");
                });

            modelBuilder.Entity("ArmazingXStock.Api.Models.Categoria", b =>
                {
                    b.Navigation("TiposProdutos");
                });

            modelBuilder.Entity("ArmazingXStock.Api.Models.Corredor", b =>
                {
                    b.Navigation("Ruas");
                });

            modelBuilder.Entity("ArmazingXStock.Api.Models.Fornecedor", b =>
                {
                    b.Navigation("ProdutosFornecedores");
                });

            modelBuilder.Entity("ArmazingXStock.Api.Models.Modulo", b =>
                {
                    b.Navigation("Niveis");
                });

            modelBuilder.Entity("ArmazingXStock.Api.Models.Nivel", b =>
                {
                    b.Navigation("Enderecos");
                });

            modelBuilder.Entity("ArmazingXStock.Api.Models.Produto", b =>
                {
                    b.Navigation("ProdutosFornecedores");
                });

            modelBuilder.Entity("ArmazingXStock.Api.Models.Rua", b =>
                {
                    b.Navigation("Modulos");
                });

            modelBuilder.Entity("ArmazingXStock.Api.Models.TipoProduto", b =>
                {
                    b.Navigation("Produtos");
                });
#pragma warning restore 612, 618
        }
    }
}
